### ISSUE TITLE
add polish as new language

### ISSUE THREAD

**Issue by dwes** [flowplayer/translations#12]
previous platform player supports polish so we need to add it to our translations plugin

**Comment by emanuelflowplayer** [comment]
I have asked Pawel to contribute translations in Polish to this file:
https://docs.google.com/spreadsheets/d/1mcVim0-rbPYk-cfibzkNcfbu4-A7j3ZG4tLxxfAS6p0/edit#gid=0

**Comment by emanuelflowplayer** [comment]
Polish translations are now available in the translation file!
